### ISSUE TITLE
3 minor issues in gdip_all.ahk

### ISSUE THREAD

**Issue by telppa** [marius-sucan/Quick-Picto-Viewer#10]
1. Gdip_AddPathPie() should be placed near Gdip_AddPathPieC().

2. Gdip_AddPathToPath() should be renamed to Gdip_AddPathPath(), or for compatibility reasons, keep Gdip_AddPathToPath() unchanged but add Gdip_AddPathPath().

3. Gdip_GaussianBlur() always returns -2. Because pEffect and zBitmap do not exist.

**Comment by marius-sucan** [comment]
Thank you very much . All fixed.

I will push the updates with the new Quick Picto Viewer release I am working on.

Best regards, Marius.
