### ISSUE TITLE
CreatePointsF() should take two types of inPoints.

### ISSUE THREAD

**Issue by telppa** [marius-sucan/Quick-Picto-Viewer#11]
The description of CreatePointsF() says that inPoints supports two types (string and array) of parameters.

However, it seems that only string are actually supported.

I hope it supports that
If inPoints is arr, like `inPoints := "[[x1,y1], [x2,y2], [x3,y3], [x4,y4]]"`

**Comment by marius-sucan** [comment]
Hello!

Thank you for the feedback.

The function does accept arrays, but not like you defined it. The accepted form of arrays are monodimensional: `array := [x1, y1, x2, y2, x3, y3...]`.

The function begins with:

```
CreatePointsF(ByRef PointsF, inPoints, dtype:="float", ds:=4) {
   If IsObject(inPoints)
   {
      PointsCount := inPoints.Length()
      VarSetCapacity(PointsF, ds * PointsCount, 0)
      Loop % PointsCount
          NumPut(inPoints[A_Index], &PointsF, ds * (A_Index-1), dtype)
      Return PointsCount//2
   } Else 
   {
      // parse given string
    }
}
```

Any function that relies on CreatePointsF() accepts arrays as I described.

Best regards, Marius.
