### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by XxnittanixX** [marius-sucan/Quick-Picto-Viewer#14]
affinity photo like lighting   tool

you have a spot and you put a bright  light onto the picture adjust opacity 

or you have a cone and is able to mve it around the picture to  make a light beam

**Comment by marius-sucan** [comment]
Hello there! 

Yes, I've drawn inspiration from affinity photo, Corel painter and Photoshop. 

However, I **do not** intend to outdo them ^_^.

Thank you. 

Best regards, Marius.
