### ISSUE TITLE
can i help with brush textures? 

### ISSUE THREAD

**Issue by XxnittanixX** [marius-sucan/Quick-Picto-Viewer#15]
id be down to help with brush texture creation

**Comment by marius-sucan** [comment]
Yes, you can contribute with brush textures, but please have them created at the same size (resolution) as the ones I have.

And please give them names. Currently, my textures lack descriptive names... 

Thank you. 

Best regards, Marius.

**Comment by XxnittanixX** [comment]
can you add  brushes
is there a specific type

**Comment by XxnittanixX** [comment]
and the vector what  did you use to create that

**Comment by marius-sucan** [comment]
I don't understand the questions.

Please reformulate the questions clearer.
