### ISSUE TITLE
line 013 MaineExe := AhkExported() in module-interface.ahk  call to non existent function  specifically AhkExported

### ISSUE THREAD

**Issue by XxnittanixX** [marius-sucan/Quick-Picto-Viewer#16]
welp hope that help

line 013 MaineExe := AhkExported() in module-interface.ahk  call to non existent function  specifically AhkExported

im running this  with the previous last two versions  is there a  runtime i need or something if so  you could make  a  if error  than  open  specified url  or something ...

**Comment by marius-sucan** [comment]
You need to run this with ahk-h.
