### ISSUE TITLE
side project? 

### ISSUE THREAD

**Issue by XxnittanixX** [marius-sucan/Quick-Picto-Viewer#18]
gpick clone for windows? please ill even pay you

**Comment by XxnittanixX** [comment]
you also have to   put terminal options  in there too please .... ill start with 25

**Comment by marius-sucan** [comment]
You want me to develop for you an application to clone windows?

**Comment by XxnittanixX** [comment]
no gpick is a color picking tool  id like to have it  scripted in autohotkey  and im sure it will get alot of attention in the windows community. after all its installed in alot of linux computers

**Comment by marius-sucan** [comment]
Thank you , but I am not interested in doing this.

Best regards, Marius.
