### ISSUE TITLE
Can I create a wia object directly using HBITMAP?

### ISSUE THREAD

**Issue by sanmaodo** [marius-sucan/Quick-Picto-Viewer#19]
A question about wia.ahk.
Can I create a wia object directly using HBITMAP?
instead of saving as a document and then creating.

@marius-sucan Thank you very much for your Quick-Picto-viewer, which is very powerful.

**Comment by marius-sucan** [comment]
Hello!

Thank you .

I am not aware of a direct way to create a WIA image object directly from a GDI hBitmap. Although, it might be possible. Why would you want it? Everything you can do with WIA can be done with GDi and GDI+.

You may look into WIA_CreateImage() , which allows you create an image by feeding it an array of pixels. But this would probably be slow for large images.

Best regards, Marius.

**Comment by sanmaodo** [comment]
HBITMAP comes from an external program
Usually, I save it as a file and create it as a WIA object for image rotation.
It's a hassle, so I want to simplify it.

maybe i should try using gdi.
Thanks for your advice!

**Comment by marius-sucan** [comment]
No worries about it. Good luck with it. If you fail, just use GDI+. Convert the hbitmap to GDI+, rotate and then save the file with GDI+. 

Best regards, Marius.
