### ISSUE TITLE
Show next image after deletion/moving of previous one

### ISSUE THREAD

**Issue by hoppfrosch** [marius-sucan/Quick-Picto-Viewer#2]
Sighting huge amounts of images (I had to review thousands of pictures taken by a wildlife camera for images with animals in it) the following functionality would be REALLY helpful:

Having an image on screen, deleting it, PictoViewer should delete the image AND show up the next image. This could/should be offered as an option ("Proceed to next image after deletion?")

Same feature would be nice for moving images: after moving an image the next image should show up (without additional user input)

In context of a simple review process it would be very helpful to have "one-keypress" actions:
* Keypress: move image to a (predefined) location and show up next image
* Another keypress: move image to another (predefined) location and show up next image

The predefined locations might be a directory, recycle bin or "nirvana" (immediately delte the image without recycle bin)

**Comment by marius-sucan** [comment]
Thank you for the suggestion. This will be implemented as a generalized solution:

There will be a specific shortcut key for «quick action» and then, a panel to choose what action to perform on key press (move, delete, copy) and configure destination. And in the same panel, an option to perform after: go to next/previous image.

Please let me know if this sounds reasonable for you . 

Please consider you could use Tab to select image even if you are in the image view. Suggested approach: pressing Page up/down [to go through them] and Tab to select the image you want. After you went through all of them, you can perform move/copy/delete only once on the selected images. You can quickly review the ones you have selected already by Ctrl + Left/Right or pressing Enter [to switch to thumbs list].

Best regards, Marius.

**Comment by hoppfrosch** [comment]
Thanks for your quick reponse

Your suggestion sounds great - buuuut ... (you know, customers are never easy to be satisfied ;-) )
I would prefer to have more than one definable quickaction - this would allow to move images to different "baskets" with minimal key/mousepresses. For example:
Key "1" puts my current images with a birds in it into my folder "birds", key "2" the current mammal-image into folder "mammals", "3" to insects and finally "4" deletes the image .

Your explanation, how this currently can be done is great, didn't know about it yet. The main drawback in my case is, that one has to go through the image stack several times: first pass delete all needless images, second pass select all bird images, and so on ... And several passes are quite a pain if you have hundreds or thousands of images like in my case.

**Comment by marius-sucan** [comment]
Your explanation makes sense and I will just expand upon my already presented idea:

I will have the keys from 1 to 5 be quick options... Five are enough ^_^ . And the panel will allow you customize as previously explained, the same options, but for each of these five keys. I could have '6' open the configuration panel itself.

I have an additional idea: How about «1» is for copy, and shift+1 is for move? And in the panel, you only have two options as possible actions for each key: move/copy  and the 2nd is delete. When delete is chosen and '1' is pressed, it is moved to recycle but with  shift+1, the file is permanently deleted.  What do you think?  Hope I was clear enough.

8 will be reserved for audio level adjusting and, 9 and 0, for rotation of image in viewport.

**Comment by hoppfrosch** [comment]
Sounds great to me! Five are  enough (even in my eyes) ....

What would be nice: If the move/deletion destination history would be stored - so you wont have to reconfigure it when you need to use a previously used destination.

Thanks!

**Comment by marius-sucan** [comment]
Yes, definitely. The settings will be stored and reloaded. Thank you for the nice feature suggestion!

I'll try to implement this new feature in the next version.

Best regards, Marius.

**Comment by marius-sucan** [comment]
Hello!

The feature you requested has now been implemented and published in v4.7.6. Please let me know how you find it, or if you have other suggestions.

Thank you .

Best regards, Marius.

**Comment by hoppfrosch** [comment]
First: sorry for the late response, was very busy the last time

After using it the first time it looks quite good - this makes sighting (sorting and deleting) of big amounts of images much faster for me...

Thanks a lot for the fast implementation and your REALLY GREAD Picto-Viewer

**Comment by marius-sucan** [comment]
Hey, no problem about the late reply.

I'm glad you like it.

I'm currently working on improving duplicate images detection by an option to actually calculate the hamming distance between the image hashes. 

The new version will have important bug fixes related to Sqlite files list database usage and performance improvements to database loading. 

And probably more... I'm interested to try to further improve the performance of how statistics are generated and how image data is collected (hashes and histogram points)... It's kinda slow when dealing with over a million images. ^_^

If you have any questions or comments about this, please do not hesitate to write back. 

Best regards, Marius.

**Comment by hoppfrosch** [comment]
> _I'm currently working on improving duplicate images detection by an option to actually calculate the hamming distance between the image hashes._

Sounds very interesting ... will there be a possibility to determine a similarity value between images? This might be interesting in my use case: a fixed (wildlife) camera which always has the same scene in focus. Most of the images are triggered by small movement of plants (due wind) and a few images with "bigger changes", as an animal occurs on the image. If there would be support by identifying images with a similarity above a threshhold, this might help separating interesting images (with animals) from randon images (with wind movement of plants only).

**Comment by marius-sucan** [comment]
Yes, there will be a similarity threshold to set. Could you please provide me with a set to test upon and improve things if possible?

The current version might be able to identify slightly different images (minimal plant movements and color deviations). You have to select "custom mode", and then precision 3, aspect ratio, and in the second tab, inner area or simplified. 

Best regards, Marius.

**Comment by marius-sucan** [comment]
Hello!

Today I released the new version of QPV. Version 4.9.6. It includes what was mentined earlier. You can give it a try and hopefully, it works as needed.

Best regards, Marius.

**Comment by hoppfrosch** [comment]
Works perfectly as I wanted.

I will try to customize QVP for my needs, to have "MOVE" as default action rather than "COPY" (When rereading the folder to be sorted, all the copied pictures are still within the folder - and I have to skip them. Using the "SHIFT" modifier within QVP allows moving the pictures - but pressing two keys for each image while reviewing thousands of images for moving the image  is not effective enough for my purposes ;-))

**Comment by marius-sucan** [comment]
Yes, it can be annoying to press shift for every move when one wants just that...

How do you find the duplicates finder? Does it suit your needs?

Best regards, Marius.

**Comment by hoppfrosch** [comment]
To be honest: I do not know, how to find duplicates with QVP

I found following menu item: MENU > File index/list > Find duplicate Images ... but I cannot figure out how to use it ...

**Comment by marius-sucan** [comment]
1. MENU > File index/list > Save files list as .SLD.
2. Choose SLDB type/format in the dropdown list.
3. Save file.
4. Go to MENU > File index/list > Find duplicate images
5. It will show a panel with tons of options, click on «Collect files data». Wait for it to finish [or not]. It can resume later the process.
6. When done, in the same panel, just use the first preset and select «Find duplicates» button.
7. To control the behavior, use the custom preset and read the help provided. There is a help button in the window.

Best regards, Marius.

**Comment by hoppfrosch** [comment]
Trying to save as SLDB I get the following error

---------------
Unable to create SQL Database file: Please choose the plain-text format to save the filelist (slideshow)

Error details  Invalid database handle

---------------

There is no sqlite.dll or sqlite.exe available on my system yet (actuially there is one ... but not on my PATH or in the current directory or script-directory ... ;-))

**Comment by marius-sucan** [comment]
Please download the provided zip file package of QPV. In there you can find the correct DLL files for SQL lite and free image.

Zip package.
http://marius.sucan.ro/media/files/blog/ahk-scripts/quick-picto-viewer-compiled.zip

By downloading different DLL versions, unexpected results may occur. 

Best regards, Marius.
