### ISSUE TITLE
may error of `If legacy `

### ISSUE THREAD

**Issue by CoffeeChaton** [marius-sucan/Quick-Picto-Viewer#20]
## may error

```ahk
            If FileRexists(imgPath)
            {
                currentFileIndex := detectFileID(imgPath)
                If (allowRecordHistory=1)
                    IniWrite, % imgPath, % mainSettingsFile, General, LastOpenedImg

                IDshowImage(currentFileIndex)
                ;  VVVVVVVVVVVVVVVVVVVV at line 588110
            } Else If OutFileName != ""
            {
                FriendlyName := FileExist(imgPath) ? "malformed" : "inexistent"
                msgBoxWrapper(appTitle ": ERROR", "Error opening file: " OutFileName ". It seems to be " FriendlyName " .`n`nAnother file from the folder will be displayed now. Files indexed: " groupDigits(maxFilesIndex) ".", 0, 0, "error")
                RandomPicture()
            }
```

The file is too big, github won't let me copy the link...
at quick-picto-viewer.ahk , line 588110 

```ahk
OutFileName := ""
If OutFileName != "" ; is mean caseB
{
    MsgBox, % "OutFileName True" ;<--
} else {
    MsgBox, % "OutFileName False"
}

caseA := ""
If (caseA != "") ; not space
{
    MsgBox, % "caseA True"
} else {
    MsgBox, % "caseA False" ;<--
}

caseB := ""
If (caseB != """") ; not equal one "
{
    MsgBox, % "caseB True" ;<--
} else {
    MsgBox, % "caseB False"
}
```

> ahk v1 doc [If (Expression)](https://www.autohotkey.com/docs/v1/lib/IfExpression.htm)
> `if FoundColor != Blue` is `if (FoundColor != "Blue")`

In this file, you only have this line that uses traditional `IF legacy`, not `if ()` or its variations, so I think this may be a potential bug.

## other

you can add this at file top, not only in comment, 
I think this will let lower versions ahk to have better startup reminders.

```ahk
#Requires AutoHotkey v1.1.33.10+
```

**Comment by marius-sucan** [comment]
Thank you very much <3.

I just pushed a commit with your suggestions.
https://github.com/marius-sucan/Quick-Picto-Viewer/commit/777a9bac81c4fecbedb63ed7ed42ea2156849050

Please let me know if you find any other bugs.

Best regards, Marius.
